import java.sql.CallableStatement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class DangKy extends javax.swing.JFrame {

    /**
     * Creates new form DangKy
     */
    private TTT game;
    int DKQ;
    public DangKy(TTT game) {
        initComponents();
        this.game = game;
        setSize(395,320);
        setLocationRelativeTo(null);
        if(game.Quyen == 1)
            cbQ.setVisible(true);
        else
            cbQ.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTK = new javax.swing.JTextField();
        txtTDN = new javax.swing.JTextField();
        btnDK = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnLL = new javax.swing.JButton();
        txtMK = new javax.swing.JPasswordField();
        cbQ = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đăng ký");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("THÔNG TIN ĐĂNG KÝ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tài khoản: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Tên người chơi: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Mật khẩu: ");

        txtTK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtTDN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnDK.setBackground(new java.awt.Color(0, 102, 102));
        btnDK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDK.setText("Đăng kí");
        btnDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDKActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(0, 102, 102));
        btnThoat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnLL.setBackground(new java.awt.Color(0, 102, 102));
        btnLL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLL.setText("Làm lại");
        btnLL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLLActionPerformed(evt);
            }
        });

        txtMK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cbQ.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbQ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTK)
                                    .addComponent(txtTDN)
                                    .addComponent(txtMK, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnDK)
                        .addGap(36, 36, 36)
                        .addComponent(btnLL)
                        .addGap(36, 36, 36)
                        .addComponent(btnThoat)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLL)
                        .addComponent(btnThoat))
                    .addComponent(btnDK))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnLLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLLActionPerformed
        txtTK.setText("");
        txtMK.setText("");
        txtTDN.setText("");
        txtTK.requestFocus();
    }//GEN-LAST:event_btnLLActionPerformed

    private void btnDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDKActionPerformed
        if(cbQ.getSelectedItem()=="User")
            DKQ = 0;
        else
            DKQ = 1;
        String taikhoan = txtTK.getText();
        String tendn = txtTDN.getText();
        String matkhau = String.valueOf(txtMK.getPassword());
        matkhau = Connect.MD5(matkhau);
        if(taikhoan.equals("") || tendn.equals("") || matkhau.equals("")){
            JOptionPane.showMessageDialog(this,"Bạn phải nhập đầy đủ thông tin","Thông báo",JOptionPane.INFORMATION_MESSAGE);
            txtTK.requestFocus();
        }
        else {
            String errConnect = Connect.getConnection();
            if (!errConnect.equals(""))
                JOptionPane.showMessageDialog(this,errConnect,"Lỗi",JOptionPane.ERROR_MESSAGE);
            else{
                String sql = "{call ThemUser(?,?,?,?,?)}";
                CallableStatement cstm;
                String kq;
                try {
                    cstm = Connect.conn.prepareCall(sql);
                    cstm.setString(1,taikhoan);
                    cstm.setString(2,tendn);
                    cstm.setString(3,matkhau);
                    cstm.setInt(4, DKQ);
                    cstm.registerOutParameter(5, java.sql.Types.NVARCHAR);
                    cstm.execute();
                    kq = cstm.getString(5);
                    JOptionPane.showMessageDialog(this,kq,"Thông báo",JOptionPane.INFORMATION_MESSAGE);
                    cstm.close();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,"Lỗi: "+ e.getMessage(),"Lỗi",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnDKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDK;
    private javax.swing.JButton btnLL;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> cbQ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtMK;
    private javax.swing.JTextField txtTDN;
    private javax.swing.JTextField txtTK;
    // End of variables declaration//GEN-END:variables
}
