
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class LichSu extends javax.swing.JFrame {
    public void DocKQ(){
        String sql;
        if(game.Quyen == 0){
            sql = "select * from RESULTS where username1 = N'"+game.Name+"' or username2 = N'"+game.Name+"'";
            btnX.setVisible(false);
            btnFull.setVisible(false);
            cbU.setVisible(false);
        }  
        else{
            sql = "select * from RESULTS where username1 = N'"+cbU.getSelectedItem().toString()+"' or username2 = N'"+cbU.getSelectedItem().toString()+"'";
            game.Quyen = 0;
        } 
        Statement stmt;
        String data;
        try {
            stmt = Connect.conn.createStatement();
            try(ResultSet rs = stmt.executeQuery(sql)){
                data ="Thời điểm\t\tTrận đấu giữa\t\tĐiểm X\tĐiểm O\tNgười thắng\n";
                while(rs.next()){
                    data += rs.getString("timeresult") + "\t" ;
                    data += rs.getString("UserName1")+" VS "+ rs.getString("UserName2") + "\t";
                    data += rs.getInt("Usermark1") + "\t" ;
                    data += rs.getInt("UserMark2") + "\t" ;
                    data += rs.getString("result") + "\t" ;
                    data += "\n";
                }
                txtLS.setText(data);
                rs.close();
            }
            stmt.close();
        } catch (Exception e) {
            txtLS.setText("Lỗi: "+e);
        }   
    }
    public void fullKQ(){
        String errConnect = Connect.getConnection();
        if(!errConnect.equals("")){
            JOptionPane.showMessageDialog(this, errConnect, "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else{
        String sql = "select * from RESULTS";
        Statement stmt;
        String data;
        try {
            stmt = Connect.conn.createStatement();
            try(ResultSet rs = stmt.executeQuery(sql)){
                data ="Thời điểm\t\tTrận đấu giữa\t\tĐiểm X\tĐiểm O\tNgười thắng\n";
                while(rs.next()){
                    data += rs.getString("timeresult") + "\t" ;
                    data += rs.getString("UserName1")+" VS "+ rs.getString("UserName2") + "\t";
                    data += rs.getInt("Usermark1") + "\t" ;
                    data += rs.getInt("UserMark2") + "\t" ;
                    data += rs.getString("result") + "\t" ;
                    data += "\n";
                }
                txtLS.setText(data);
                rs.close();
            }
            stmt.close();
        } catch (Exception e) {
            txtLS.setText("Lỗi: "+e);
        }
        }
    }
    
    /**
     * Creates new form LichSu
     */
    private TTT game;
    public LichSu(TTT game) {
        initComponents();
        this.game = game;
        String sqlString = "select * from users";
        Statement stmt;
        try{
            stmt = Connect.conn.createStatement();
            try(ResultSet rs = stmt.executeQuery(sqlString)){
                while(rs.next()){
                    cbU.addItem(rs.getString("name"));
                }
                rs.close();
            }
            stmt.close();
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "LỖi: "+ e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLS = new javax.swing.JTextArea();
        btnOK = new javax.swing.JButton();
        cbU = new javax.swing.JComboBox<>();
        btnFull = new javax.swing.JButton();
        btnX = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LỊch sử");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("LỊCH SỬ CHƠI GAME TIC TAC TOE");

        txtLS.setColumns(20);
        txtLS.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtLS.setRows(5);
        txtLS.setEnabled(false);
        jScrollPane1.setViewportView(txtLS);

        btnOK.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnOK.setForeground(new java.awt.Color(0, 102, 102));
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        cbU.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUActionPerformed(evt);
            }
        });

        btnFull.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFull.setText("Tất cả");
        btnFull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFullActionPerformed(evt);
            }
        });

        btnX.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnX.setText("Xoá");
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jLabel1)
                        .addGap(0, 352, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(511, 511, 511)
                .addComponent(btnOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFull)
                .addGap(18, 18, 18)
                .addComponent(cbU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnX)
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFull)
                    .addComponent(btnX))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOK)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void cbUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUActionPerformed
        DocKQ();
    }//GEN-LAST:event_cbUActionPerformed

    private void btnFullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFullActionPerformed
        fullKQ();
    }//GEN-LAST:event_btnFullActionPerformed

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
        String err = Connect.getConnection();
        if(!err.equals("")){
            JOptionPane.showMessageDialog(this, err, "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else{
            String sql = "delete results where username1 = N'" + cbU.getSelectedItem().toString()+"' or username2 = N'" + cbU.getSelectedItem().toString()+"'";
            Statement stmt;
            try{
                stmt = Connect.conn.createStatement();
                int row = stmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(this,"Đã xoá "+row+" dòng lịch sử của người chơi "+cbU.getSelectedItem().toString(),"Thông báo",JOptionPane.INFORMATION_MESSAGE);
                DocKQ();
                stmt.close();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, err);
            }
        }
    }//GEN-LAST:event_btnXActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFull;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnX;
    private javax.swing.JComboBox<String> cbU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtLS;
    // End of variables declaration//GEN-END:variables
}
